# Generated by Django 3.0.6 on 2020-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.TextField(max_length=50)),
                ('type', models.CharField(choices=[('laptop', 'laptop'), ('desktop', 'desktop')], max_length=50)),
                ('processor', models.TextField(max_length=50)),
                ('werkgeheugen', models.TextField(max_length=50)),
                ('defecten', models.TextField(max_length=50)),
            ],
        ),
    ]
