# Generated by Django 3.0.6 on 2020-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratiesysteem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='afbeelding',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
