# Generated by Django 3.0.6 on 2020-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratiesysteem', '0002_computer_afbeelding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='afbeelding',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
