# Generated by Django 3.0.6 on 2020-06-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratiesysteem', '0003_auto_20200614_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='gerepareerd',
            field=models.BooleanField(default=False),
        ),
    ]
